dist: bionic
language: rust
rust:
  - nightly
cache: cargo
before_script:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  - brew tap riscv/riscv
  - brew install riscv-tools qemu
  - cargo install cargo-xbuild cargo-binutils
  - rustup component add rust-src llvm-tools-preview rustfmt rls rust-analysis
  - rustup target add riscv64gc-unknown-none-elf
script:
  - make all
  - make docs
