[package]
name = "core-os-riscv"
version = "0.1.0"
authors = ["Alex Chi <iskyzh@gmail.com>"]
edition = "2018"

[dependencies]
riscv = "0.5.4"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
